### ISSUE TITLE
Number of attempts not working

### ISSUE THREAD

**Issue by itinspectorio** [Sdelsaz/PIN-for-Admin#1]
Dear Sdelsaz,
As I checked almost everything is working as needed except number of allowed attempts. I checked via Jamf Pro by setting default 3 or more attempts, but on test machine - still the amount of allowed number is not set and in code I dont see where MaxAttempt value is used in code to prevent user after specific number allowed.

**Comment by Sdelsaz** [comment]
Hi,

I just tested the script again and the maximum attempts are working fine. Make sure the maximum number of attempts is set in Parameter 6 in the policy.  Line number 112 makes sure the prompts happen while the pin is incorrect and the number of attempts is not exceeded.

**Comment by karlthreads** [comment]
Dear Sdelsaz,

The script works excellent to make standard user admin but once the time elapses the user is not demoted, they remain as admin. M1, Ventura 13.6.4.

**Comment by Sdelsaz** [comment]
Hi Karl,

The demotion not working might indicate the PPPC profile is not installed.  (See the PPPC Profile example in the repository) This profile is required for the demotion to work.

**Comment by karlthreads** [comment]
Ah thank you, I had installed but not scoped. Many thanks!
